author: Jörn-Thorben Hinz
name: Build Debian packages
description: Build Debian packages with dpkg-buildpackage in a flexible environment.
inputs:
  apt-opts:
    description: Options to be passed to apt-get
    required: false
  artifacts-dir:
    default: debian/artifacts
    description: Directory path relative to $GITHUB_WORKSPACE to place the built packages in
    required: true
  before-build-hook:
    description: Shell command(s) to execute after installing build dependencies
      and before executing dpkg-buildpackage
    required: false
  buildpackage-opts:
    description: Options to be passed to dpkg-buildpackage
    required: false
  docker-image:
    default: debian:stable-slim
    description: Name of a Docker image or path of a Dockerfile to use for the build container
    required: true
  extra-build-deps:
    description: Extra packages to be installed as build dependencies
    required: false
  extra-docker-args:
    description: Additional arguments to 'docker run' when starting the build container
    required: false
  extra-repo-keys:
    description: Extra ASCII-armored APT repository keys or paths to keyring files to trust in the build environment
    required: false
  extra-repos:
    description: Extra APT repositories to configure in the build environment (one-line-style or deb822-style format)
    required: false
  host-arch:
    description: Foreign architecture to setup cross-building for
    required: false
  setup-hook:
    description: Shell command(s) to execute after setting-up the build
      environment and before installing build dependencies
    required: false
  source-dir:
    default: ./
    description: Path relative to $GITHUB_WORKSPACE that contains the package sources
    required: true
outputs:
  artifacts:
    description: Newline-separated list of artifacts (the .buildinfo, .changes
      and .deb files); the list contains their paths relative to the workspace
    value: ${{ steps.run.outputs.ARTIFACTS }}
runs:
  using: composite
  steps:
    - env:
        # Manually setting INPUT_* variables here until
        # https://github.com/actions/runner/issues/665 is resolved:
        INPUT_APT_OPTS: ${{ inputs.apt-opts }}
        INPUT_ARTIFACTS_DIR: ${{ inputs.artifacts-dir }}
        INPUT_BEFORE_BUILD_HOOK: ${{ inputs.before-build-hook }}
        INPUT_BUILDPACKAGE_OPTS: ${{ inputs.buildpackage-opts }}
        INPUT_DOCKER_IMAGE: ${{ inputs.docker-image }}
        INPUT_EXTRA_BUILD_DEPS: ${{ inputs.extra-build-deps }}
        INPUT_EXTRA_DOCKER_ARGS: ${{ inputs.extra-docker-args }}
        INPUT_EXTRA_REPO_KEYS: ${{  inputs.extra-repo-keys }}
        INPUT_EXTRA_REPOS: ${{  inputs.extra-repos }}
        INPUT_HOST_ARCH: ${{ inputs.host-arch }}
        INPUT_SETUP_HOOK: ${{ inputs.setup-hook }}
        INPUT_SOURCE_DIR: ${{ inputs.source-dir }}
      id: run
      run: ${{ github.action_path }}/scripts/run
      shell: bash
    - env:
        BUILD_DIR: ${{ steps.run.outputs.build-dir }}
      if: ${{ always() && steps.run.outputs.build-dir != '' }}
      run: ${{ github.action_path }}/scripts/post
      shell: bash
branding:
  color: red
  icon: package
