author: Jörn-Thorben Hinz
name: Build Debian packages
description: Build Debian packages with dpkg-buildpackage in a flexible environment.
inputs:
  apt-opts:
    description: Options to be passed to apt-get
    required: false
  artifacts-dir:
    default: debian/artifacts
    description: Directory path relative to $GITHUB_WORKSPACE to place the built packages in
    required: true
  buildpackage-opts:
    description: Options to be passed to dpkg-buildpackage
    required: false
  docker-image:
    default: debian:stable-slim
    description: Name of a Docker image to build inside or path of a Dockerfile
    required: true
  extra-build-deps:
    description: Extra packages to be installed as build dependencies
    required: false
  extra-docker-args:
    description: Additional arguments to 'docker run' when starting the build container
    required: false
  host-arch:
    description: Foreign architecture to setup cross-compilation for
    required: false
  source-dir:
    default: ./
    description: Path relative to $GITHUB_WORKSPACE that contains the package sources
    required: true
runs:
  using: composite
  steps:
    - env:
        # Manually setting INPUT_* variables here until
        # https://github.com/actions/runner/issues/665 is resolved:
        INPUT_APT_OPTS: ${{ inputs.apt-opts }}
        INPUT_ARTIFACTS_DIR: ${{ inputs.artifacts-dir }}
        INPUT_BUILDPACKAGE_OPTS: ${{ inputs.buildpackage-opts }}
        INPUT_HOST_ARCH: ${{ inputs.host-arch }}
        INPUT_DOCKER_IMAGE: ${{ inputs.docker-image }}
        INPUT_EXTRA_BUILD_DEPS: ${{ inputs.extra-build-deps }}
        INPUT_EXTRA_DOCKER_ARGS: ${{ inputs.extra-docker-args }}
        INPUT_SOURCE_DIR: ${{ inputs.source-dir }}
      run: ${{ github.action_path }}/scripts/run.sh
      shell: bash
branding:
  color: red
  icon: package
