#!/bin/sh

set -eu

export DEBIAN_FRONTEND=noninteractive

apt-get update --quiet $BDP_APT_OPTS

apt-get install --no-install-recommends --quiet --yes $BDP_APT_OPTS -- dpkg-dev $BDP_EXTRA_BUILD_DEPS

# Calling `apt-get build-dep` with ./ here to easily keep compatibility with
# old apt versions
apt-get build-dep --no-install-recommends --quiet --yes $BDP_APT_OPTS -- "$BDP_SOURCES_DIR"
