#!/bin/sh

set -eu

# Usage:
#   mv_artifact ARTIFACT_PATH DEST_DIR
mv_artifact()
{
	ad=$(dirname "$1")
	if [ "$(realpath "$ad")" != "$(realpath "$2")" ]; then
		mv -- "$1" "$2"
		echo "Moved $(basename "$1")"
	fi
}

# Usage:
#   mv_other_artifact BUILDINFO_PATH OTHER_EXT DEST_DIR
mv_other_artifact()
{
	a=${1%.buildinfo}$2
	[ ! -f "$a" ] || mv_artifact "$a" "$3"
}

mkdir -p -- "$BDP_ARTIFACTS_DIR"

while read -r l; do
	artifact=$BDP_SOURCES_DIR/../${l%% *}
	mv_artifact "$artifact" "$BDP_ARTIFACTS_DIR"
	case "$artifact" in
		*.buildinfo)
			# Ignoring the stuff generated by dpkg-source here for now.
			mv_other_artifact "$artifact" .changes "$BDP_ARTIFACTS_DIR"
			;;
	esac
done < "$BDP_SOURCES_DIR/debian/files"
